export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';

export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAILURE = 'UPDATE_AVATAR_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const LOAD_DIRECTORY_REQUEST = 'LOAD_DIRECTORY_REQUEST';
export const LOAD_DIRECTORY_SUCCESS = 'LOAD_DIRECTORY_SUCCESS';
export const LOAD_DIRECTORY_FAILURE = 'LOAD_DIRECTORY_FAILURE';

export const LOAD_LINK_REQUEST = 'LOAD_LINK_REQUEST';
export const LOAD_LINK_SUCCESS = 'LOAD_LINK_SUCCESS';
export const LOAD_LINK_FAILURE = 'LOAD_LINK_FAILURE';

export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';
export const GET_LINKS_REFRESH = 'GET_LINKS_REFRESH';

export const LOAD_COMMENTS_REQUEST = 'LOAD_COMMENTS_REQUEST';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_COMMENTS_FAILURE = 'LOAD_COMMENTS_FAILURE';
export const LOAD_COMMENTS_REFRESH = 'LOAD_COMMENTS_REFRESH';

export const NEW_COMMENT_REQUEST = 'NEW_COMMENT_REQUEST';
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS';
export const NEW_COMMENT_FAILURE = 'NEW_COMMENT_FAILURE';

export const POST_NEW_LINK_REQUEST = 'POST_NEW_LINK_REQUEST';
export const POST_NEW_LINK_SUCCESS = 'POST_NEW_LINK_SUCCESS';
export const POST_NEW_LINK_FAILURE = 'POST_NEW_LINK_FAILURE';

export const VOTE_LINK_REQUEST = 'VOTE_LINK_REQUEST';
export const VOTE_LINK_SUCCESS = 'VOTE_LINK_SUCCESS';
export const VOTE_LINK_FAILURE = 'VOTE_LINK_FAILURE';

export const GET_DEFAULT_DIRECTORIES_REQUEST = 'GET_DEFAULT_DIRECTORIES_REQUEST';
export const GET_DEFAULT_DIRECTORIES_SUCCESS = 'GET_DEFAULT_DIRECTORIES_SUCCESS';
export const GET_DEFAULT_DIRECTORIES_FAILURE = 'GET_DEFAULT_DIRECTORIES_FAILURE';

export const SET_PAGE_INFO = 'SET_PAGE_INFO';
export const SET_DIRECTORY_SORT_OPTION = 'SET_DIRECTORY_SORT_OPTION';
